# Generated by Django 2.0 on 2017-12-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dive_title', models.CharField(max_length=200, verbose_name='dive title')),
                ('dive_date', models.DateTimeField(verbose_name='date of dive')),
            ],
        ),
    ]
